spring:
  jpa:
    hibernate:
      ddl-auto: create

    generate-ddl: on

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    sql: debug